services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:delegated
      - dados:/app/dados
    command: sh -c "php scripts/migrar_sqlite.php && php -S 0.0.0.0:8000 index.php"
    environment:
      PHP_ERROR_REPORTING: "E_ALL"
      PHP_DISPLAY_ERRORS: "1"

volumes:
  dados:
